# Generated by Django 2.0 on 2019-01-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kh', models.CharField(max_length=200)),
                ('km', models.CharField(max_length=200)),
                ('xf', models.IntegerField(null=True)),
                ('xs', models.IntegerField(null=True)),
                ('yxh', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yxh', models.CharField(max_length=200)),
                ('mc', models.CharField(max_length=200)),
                ('dz', models.CharField(max_length=200)),
                ('lxdh', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xh', models.CharField(max_length=200)),
                ('xq', models.CharField(max_length=200)),
                ('kh', models.CharField(max_length=200)),
                ('gh', models.CharField(max_length=200)),
                ('pscj', models.IntegerField(null=True)),
                ('kscj', models.IntegerField(null=True)),
                ('zpcj', models.IntegerField(null=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edu_manage.C')),
            ],
        ),
        migrations.CreateModel(
            name='O',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xq', models.CharField(max_length=200)),
                ('kh', models.CharField(max_length=200)),
                ('gh', models.CharField(max_length=200)),
                ('sksj', models.CharField(max_length=200)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edu_manage.C')),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xh', models.CharField(max_length=200)),
                ('xm', models.CharField(max_length=200)),
                ('xb', models.CharField(max_length=200)),
                ('csrq', models.DateField(null=True)),
                ('jg', models.CharField(max_length=200)),
                ('sjhm', models.CharField(max_length=200)),
                ('yxh', models.CharField(max_length=200)),
                ('psw', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gh', models.CharField(max_length=200)),
                ('xm', models.CharField(max_length=200)),
                ('xb', models.CharField(max_length=200)),
                ('csrq', models.DateField(null=True)),
                ('xl', models.CharField(max_length=200)),
                ('jbgz', models.FloatField(null=True)),
                ('yxh', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='o',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edu_manage.T'),
        ),
        migrations.AddField(
            model_name='e',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edu_manage.T'),
        ),
    ]
