# Generated by Django 2.0 on 2019-02-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t',
            name='psw',
            field=models.CharField(default='1111', max_length=200),
            preserve_default=False,
        ),
    ]
