# Generated by Django 2.0 on 2019-01-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0002_auto_20190102_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh', models.CharField(max_length=200)),
                ('km', models.CharField(max_length=200)),
                ('yxh', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yxh', models.CharField(max_length=200)),
                ('mc', models.CharField(max_length=200)),
                ('dz', models.CharField(max_length=200)),
                ('lxdz', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=200)),
                ('xq', models.CharField(max_length=200)),
                ('kh', models.CharField(max_length=200)),
                ('gh', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='O',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=200)),
                ('kh', models.CharField(max_length=200)),
                ('gh', models.CharField(max_length=200)),
                ('sksj', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh', models.CharField(max_length=200)),
                ('xm', models.CharField(max_length=200)),
                ('xb', models.CharField(max_length=200)),
                ('xl', models.CharField(max_length=200)),
                ('yxh', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
