# Generated by Django 2.0 on 2019-01-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0003_c_d_e_o_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='xf',
            field=models.IntegerField(null=True),
        ),
    ]
