# Generated by Django 2.0 on 2019-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0004_c_xf'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='xs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='e',
            name='kscj',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='e',
            name='pscj',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='e',
            name='zpcj',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='s',
            name='csrq',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='t',
            name='csrq',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='t',
            name='jbgz',
            field=models.FloatField(null=True),
        ),
    ]
