# Generated by Django 2.0 on 2019-01-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0005_auto_20190103_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='d',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='e',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='o',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='s',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='t',
            name='pub_date',
        ),
    ]
