# Generated by Django 2.0 on 2019-01-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0006_auto_20190103_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d',
            old_name='lxdz',
            new_name='lxdh',
        ),
    ]
