# Generated by Django 2.0 on 2019-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_manage', '0008_s_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='kaike',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
